name: Deploy MkDocs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install MkDocs + Material
        run: pip install mkdocs==1.5.3 mkdocs-material==9.1.10

      - name: Build and Deploy
        run: mkdocs gh-deploy --force --remote-name origin